# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 373839256ab7f49ebac10d97d2e98d3102e6a59bddfc68fd06314316e5943538158b73de03c86fc5a2104cc62be0dff06548c0eadca196cfeccaf8f9d9b499bd

test:
  secret_key_base: 84403287dd31214a46433df14775785c98f55c2dc8e777b6bec5b3b20ed6d274c068cffda7f2d9c6159e2229fa419a7e845f430b2bd5a6830f1e90faa4bc5746

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
